// Dữ liệu phim copy từ script.js để migrate sang MySQL
const IMG_BASE = "Img/";

let globalMoviesList = [
  {
    title: "Twenty Five Twenty One",
    slug: "tuoi-hai-lam-tuoi-hai-mot",
    episodes: 16,
    genres: "Tình Cảm, Học Đường, Chính Kịch, Tâm Lý, Hàn Quốc",
    poster: IMG_BASE + "2521.jpg",
    banner: IMG_BASE + "2521.jpg",
    desc: "Tại thời điểm mà những ước mơ dường như xa tầm với, một kiếm sĩ tuổi teen theo đuổi những hoài bão lớn và gặp một chàng trai chăm chỉ đang tìm cách làm lại cuộc đời.",
  },
  {
    title: "Queen of Tears",
    slug: "nu-hoang-nuoc-mat",
    episodes: 16,
    genres: "Tình Cảm, Chính Kịch, Hài Hước, Tâm Lý, Hàn Quốc",
    poster: IMG_BASE + "QueenOfTears.jpg",
    banner: IMG_BASE + "QueenOfTears.jpg",
    desc: "Cuộc sống hôn nhân sóng gió nhưng đầy cảm xúc của cặp vợ chồng tài phiệt.",
  },
  {
    title: "Mouse",
    slug: "mouse-ke-san-nguoi-ban-dien-anh",
    episodes: 20,
    genres: "Bí Ẩn, Hình Sự, Kinh Dị, Tâm Lý, Hàn Quốc",
    poster: IMG_BASE + "Mouse.jpg",
    banner: IMG_BASE + "Mouse.jpg",
    desc: "Thước phim trinh thám giật gân xoay quanh kẻ sát nhân biến thái.",
  },
  {
    title: "Moving",
    slug: "doi-thieu-nien-sieu-dang",
    episodes: 20,
    genres: "Hành Động, Viễn Tưởng, Thần Thoại, Phiêu Lưu, Hàn Quốc",
    poster: IMG_BASE + "Moving.jpg",
    banner: IMG_BASE + "Moving.jpg",
    desc: "Những siêu anh hùng ẩn giấu thân phận để bảo vệ gia đình.",
  },
  {
    title: "Can This Love Be Translated?",
    slug: "tieng-yeu-nay-anh-dich-duoc-khong",
    episodes: 12,
    genres: "Tình Cảm, Hài Hước, Hàn Quốc",
    poster: IMG_BASE + "Can_This_Love_Be_Translated.png",
    banner: IMG_BASE + "Can_This_Love_Be_Translated.png",
    desc: "Câu chuyện về những phiên dịch viên và ranh giới mong manh giữa công việc và tình cảm.",
  },
  {
    title: "My Liberation Notes",
    slug: "nhat-ky-tu-do-cua-toi",
    episodes: 16,
    genres: "Chính Kịch, Tâm Lý, Hàn Quốc",
    poster: IMG_BASE + "Nhat_ky_tu_do_cua_toi.jpg",
    banner: IMG_BASE + "Nhat_ky_tu_do_cua_toi.jpg",
    desc: "Ba anh chị em ở ngoại ô Seoul đi tìm sự giải thoát cho chính cuộc đời mình.",
  },
  {
    title: "Resident Playbook",
    slug: "chuyen-doi-bac-si-noi-tru",
    episodes: 12,
    genres: "Chính Kịch. Tình Cảm, Tâm Lý, Hàn Quốc",
    poster: IMG_BASE + "Chuyện Đời Bác Sĩ Nội Trú.jpg",
    banner: IMG_BASE + "Chuyện Đời Bác Sĩ Nội Trú.jpg",
    desc: "Nhật ký hài hước và chân thực của các bác sĩ nội trú tại bệnh viện.",
  },
  {
    title: "Teach You a Lesson",
    slug: "bai-hoc-dang-doi",
    episodes: 10,
    genres: "Hành Động, Hình Sự, Chính Kịch, Hàn Quốc",
    poster: IMG_BASE + "Teach You a Lesson.jpg",
    banner: IMG_BASE + "Teach You a Lesson.jpg",
    desc: "Hành trình đấu tranh giành lại công bằng đầy kịch tính.",
  },
  {
    title: "The Wonderfools",
    slug: "biet-doi-sieu-kho",
    episodes: 8,
    genres: "Hài Hước, Tâm Lý, Phiêu Lưu, Hàn Quôcs",
    poster: IMG_BASE + "wonderfools.jpg",
    banner: IMG_BASE + "wonderfools.jpg",
    desc: "Nhóm bạn với những giấc mơ dang dở cùng nhau vượt qua thử thách cuộc sống.",
  },
  {
    title: "We Are Trying Here",
    slug: "cuoc-chien-trong-chung-ta",
    episodes: 12,
    genres: "Tình Cảm, Tâm Lý, Gia Đình, Hàn Quốc",
    poster: IMG_BASE + "We Are All Trying Here.jpg",
    banner: IMG_BASE + "We Are All Trying Here.jpg",
    desc: "Câu chuyện ấm áp về những con người đang cố gắng hết mình mỗi ngày.",
  },
  {
    title: "Our Beloved Summer",
    slug: "mua-he-yeu-dau-cua-chung-ta-nhung-ngay-he-ruc-nang-cua-chung-minh",
    episodes: 16,
    genres: "Tình Cảm, Hài Hước, Tâm Lý, Hàn Quốc",
    poster: IMG_BASE + "Our Beloved Summer.jpg",
    banner: IMG_BASE + "Our Beloved Summer.jpg",
    desc: "Tình yêu nhẹ nhàng, sâu lắng qua những thước phim tài liệu thanh xuân.",
  },
  {
    title: "Twinkling Watermelon",
    slug: "dua-hau-lap-lanh",
    episodes: 16,
    genres: "Tình Cảm, Âm Nhạc, Học Đường, Viễn Tưởng, Hàn Quốc",
    poster: IMG_BASE + "twinkling watermelon.jpg",
    banner: IMG_BASE + "twinkling watermelon.jpg",
    desc: "Hành trình xuyên không về quá khứ qua một cửa hàng nhạc cụ kỳ lạ.",
  },
  {
    title: "weathering with you",
    slug: "dua-con-cua-thoi-tiet",
    episodes: 1,
    genres: "Hoạt Hình, Viễn Tưởng, Tình Cảm, Phim Ngắn, Anime",
    poster: IMG_BASE + "weathering with you.jpg",
    banner: IMG_BASE + "weathering with you.jpg",
    desc: "Xoay quanh cuộc sống của cậu thiếu niên Morishima Hodaka...",
  },
  {
    title: "The Witch: Part 1. The Subversion",
    slug: "sat-thu-nhan-tao",
    episodes: 1,
    genres: "Hành Động, Bí Ẩn, Khoa Học, Kinh Dị, Hàn Quốc",
    poster: IMG_BASE + "TheWitch1.jpg",
    banner: IMG_BASE + "TheWitch1.jpg",
    desc: "Sát Thủ Nhân Tạo là bộ phim hành động li kì kể về Koo Ja-yoon...",
    group: "sat-thu-nhan-tao",
    partName: "Phần 1",
  },
  {
    title: "The Witch: Part 2. The Other One",
    slug: "sat-thu-nhan-tao-2-mau-vat-con-lai",
    episodes: 1,
    genres: "Hành Động, Bí Ẩn, Khoa Học, Kinh Dị, Hàn Quốc",
    poster: IMG_BASE + "TheWitch2.jpg",
    banner: IMG_BASE + "TheWitch2.jpg",
    desc: "Lợi dụng sự cố kinh hoàng tại cơ sở thí nghiệm, cô nàng 17 tuổi...",
    group: "sat-thu-nhan-tao",
    partName: "Phần 2",
  },
  {
    title: "agent kim reactivated",
    slug: "dac-vu-kim-tai-khoi-dong",
    episodes: 10,
    genres: "Hành Động, Hình Sự, Võ Thuật, Hàn Quốc",
    poster: IMG_BASE + "AgentKimReactivated.jpg",
    banner: IMG_BASE + "AgentKimReactivated.jpg",
    desc: "Một ông bố yêu con từng là lính đặc nhiệm đáng gờm...",
  },
  {
    title: "all of us are dead",
    slug: "ngoi-truong-xac-song",
    episodes: 12,
    genres:
      "Chính kịch, Viễn Tưởng, Phiêu Lưu, Hành Động, Khoa Học,  Học Đường, Hàn Quốc",
    poster: IMG_BASE + "All of Us Are Dead.jpg",
    banner: IMG_BASE + "All of Us Are Dead.jpg",
    desc: "Một trường cấp ba trở thành điểm bùng phát virus thây ma. Các học sinh mắc kẹt phải nỗ lực thoát ra – hoặc biến thành một trong những người nhiễm bệnh hung tợn.",
  },
  {
    title: "naruto",
    slug: "naruto",
    episodes: 220,
    genres: "Hoạt Hình, Anime, Võ Thuật",
    poster: IMG_BASE + "Naruto.jpg",
    banner: IMG_BASE + "Naruto.jpg",
    desc: "Bộ phim kể về cậu về quá trình lớn lên và cuộc đời của cậu bé những nguy hiểm mà cậu đã gặp phải kèm theo đó là một động lực và niềm tin phi thường , một tâm hồn trong sáng chứa đựng những trò nghịch ngợm bướng bỉnh nhưng đầy hồn nhiên . Cùng với việc xoay quanh những người đã bỏ mạng do tranh giành quyền lực cộng với sự đau thương , mất mát mà Naruto đã trải qua.",
    group: "naruto",
    partName: "naruto",
  },
  {
    title: "naruto shippuden",
    slug: "naruto-shippuden",
    episodes: 500,
    genres: "Hoạt Hình, Anime, Võ Thuật",
    poster: IMG_BASE + "Naruto Shippuden.jpg",
    banner: IMG_BASE + "Naruto Shippuden.jpg",
    desc: "Naruto Shippuden hay còn được gọi với cái tên quen thuộc Naruto phần 2 là phần tiếp theo của bộ phim hoạt hình nổi tiếng Naruto, lấy bối cảnh hai năm rưỡi sau khi Naruto rời làng Lá. Naruto Shippuden tiếp tục theo chân chàng ninja trẻ tuổi Naruto Uzumaki trong cuộc hành trình luyện tập cực khổ để trở thành ninja giỏi nhất. Trong khi đó, Akatsuki, một tổ chức bí ẩn tập hợp những ninja phản diện tài giỏi bậc nhất, đang từng bước thực hiện kế hoạch lớn của chúng, đe dọa sự an toàn của thế giới ninja. Naruto sẽ làm gì để bảo vệ làng Lá và những người mà cậu yêu quý?",
    group: "naruto",
    partName: "naruto shippuden",
  },
  {
    title: "vincenzo",
    slug: "vincenzo",
    episodes: 20,
    genres: "Hành Động, Phiêu Lưu, Hài Hước, Chính Kịch, Hàn Quốc",
    poster: IMG_BASE + "Vincenzo.jpg",
    banner: IMG_BASE + "Vincenzo.jpg",
    desc: "Vincenzo là câu chuyện kể về một luật sư mafia người Ý gốc Hàn trốn về Hàn Quốc sau khi bị tổ chức phản bội. Khi trở lại quê hương, anh tham gia quét sạch kẻ xấu theo đúng cách của một người xấu cùng luật sư Hong Cha-yong.",
  },
  {
    title: "Hunt",
    slug: "san-lung-gian-diep",
    episodes: 1,
    genres: "Hành Động, Bí Ẩn, Tâm Lý, Hàn Quốc",
    poster: IMG_BASE + "Hunt.jpg",
    banner: IMG_BASE + "Hunt.jpg",
    desc: "Hunt lấy bối cảnh Hàn Quốc thập niên 1980, giai đoạn mà chính quyền quân sự nước này siết chặt các vấn đề liên quan đến chiến lược an ninh quốc gia. Nhân vật chính của phim là hai hai điệp viên Hàn Quốc (Lee Jung Jae và Jung Woo Sung) nhận nhiệm vụ lật mặt một gián điệp Triều Tiên trong tổ chức của mình. Trong quá trình làm nhiệm vụ, họ đã nảy sinh nghi ngờ và bắt đầu điều tra lẫn nhau.cd",
  },
  {
    title: "Money Heist: Korea - Joint Economic Area",
    slug: "phi-vu-trieu-do-han-quoc",
    episodes: 12,
    genres: "Hành Động, Bí Ẩn, Phiêu Lưu, Hình Sự, Chính Kịch, Hàn Quốc",
    poster: IMG_BASE + "Money Heist Korea.jpg",
    banner: IMG_BASE + "Money Heist Korea.jpg",
    desc: "Giáo sư (Yoo Ji-Tae) lên kế hoạch cho một vụ trộm đầy tham vọng sẽ có một khoản tiền lớn. Đối với kế hoạch của mình, Giáo sư tìm kiếm các thành viên tiềm năng trong nhóm. Các thành viên được tuyển chọn chọn tên thành phố làm mật danh và họ đều có cá tính mạnh mẽ. Kế hoạch của họ có vẻ hoàn hảo, nhưng do bắt giữ các con tin, họ phải đối mặt với một tình huống bất ngờ.",
  },
  {
    title: "Itaewon Class",
    slug: "tang-lop-itaewon",
    episodes: 16,
    genres: "Chính Kịch, Tâm Lý, Tình Cảm, Hàn Quốc",
    poster: IMG_BASE + "Itaewon Class.jpg",
    banner: IMG_BASE + "Itaewon Class.jpg",
    desc: "Tại một khu phố nhộn nhịp của Seoul, một cựu tù nhân và bạn bè mình chiến đấu với đối thủ khó nhằn để biến tham vọng quán bar đường phố của họ thành hiện thực.",
  },
  {
    title: "Nine Puzzles",
    slug: "chin-manh-ghep-bi-an",
    episodes: 11,
    genres: "Hình Sự, Bí Ẩn, Tâm Lý, Hàn Quốc",
    poster: IMG_BASE + "Nine Puzzles.jpg",
    banner: IMG_BASE + "Nine Puzzles.jpg",
    desc: "Nine Puzzles là bộ phim thuộc thể loại hình sự, phá án, kinh dị kể về hành trình truy tìm hung thủ vụ án giết người hàng loạt xảy ra 10 năm về trước nay lại tái diễn. Yoon Yi Na (Kim Da Mi thủ vai) là nhân chứng duy nhất trong vụ án 10 năm trước khi người chú ruột của cô bị sát hại. Sau này, cô trở thành trung úy cảnh sát 6 năm kinh nghiệm trong lĩnh vực lập hồ sơ phân tích tội phạm thuộc Đội phân tích tội phạm - Phòng Điều tra pháp y thuộc Cơ quan cảnh sát thành phố Seoul, với bộ não thiên tài, Yina nắm bắt rất nhanh động cơ phạm tội của hung thủ tại hiện trường như thể đã từng thực hiện. Cùng lật lại vụ án, truy tìm hung thủ giết người hàng loạt xảy ra 10 năm trước cùng với Yina là cảnh sát điều tra đội phòng chống bạo lực Kim Han Saem (Son Seok Gu thủ vai), người luôn nghi ngờ Yina chính là hung thủ của vụ án 10 năm trước. Han Saem là cảnh sát ưu tú, lỳ lợm và nhạy bén nhưng lại khiến cho người ta hiểu lầm bởi những hành động có phần quái dị của mình. Để ngăn chặn số lượng nạn nhân bị gi.ết hại ngày một tăng cùng với sự xuất hiện của “mảnh ghép bí ẩn”, Yina phải cùng bắt tay với Han Saem để nhanh chóng tìm ra hung thủ thật sự.",
  },
  {
    title: "20th Century Girl",
    slug: "co-gai-the-ky-20",
    episodes: 1,
    genres: "Tình Cảm, Chính Kịch, Hàn Quốc",
    poster: IMG_BASE + "20th Century Girl.jpg",
    banner: IMG_BASE + "20th Century Girl.jpg",
    desc: "Cô Gái Thế Kỷ 20 kể về năm 1999, một cô nàng tuổi teen theo dõi sát sao một nam sinh trong trường thay cho cô bạn thân si tình. Nhưng rồi, chính cô lại bị cuốn vào câu chuyện tình của riêng mình",
  },
  {
    title: "Duty After School",
    slug: "hoc-ky-sinh-tu",
    episodes: 10,
    genres: "Tình Cảm, Chính Kịch, Tâm Lý, Hành Động, Học Đường, Hàn Quốc",
    poster: IMG_BASE + "Duty After School.jpg",
    banner: IMG_BASE + "Duty After School.jpg",
    desc: "Học Kỳ Sinh Tử – Duty After School (2023) dựa trên webcomic “Duty After School” của Ha Il-Kwon, lấy bối cảnh Hàn Quốc bị tấn công bởi những sinh vật lạ từ trên trời rơi xuống, gây ra thảm họa thương vong toàn quốc. Để giúp đỡ các lực lượng quân sự, chính phủ Hàn chỉ định tất cả các sinh viên cũng như học sinh trung học phải trở thành quân dự bị. Thay vì ngòi bút, nay học sinh Hàn Quốc phải cầm vũ khí để tiêu diệt những sinh vật này.",
  },
  {
    title: "Study Group",
    slug: "hoc-sinh-ca-biet",
    episodes: 10,
    genres: "Tình Cảm, Hài Hước, Tâm Lý, Hành Động, học Đường, Hàn Quốc",
    poster: IMG_BASE + "Study Group.jpg",
    banner: IMG_BASE + "Study Group.jpg",
    desc: "Học Sinh Cá Biệt xoay quanh hành trình vươn lên trong học tập đầy cam go của cậu học sinh chỉ giỏi đánh nhau Yun Ga Min. Học tại một trường trung học đầy tai tiếng với thành phần học sinh đa số thuộc diện cá biệt, Ga Min vẫn nuôi quyết tâm cải thiện học lực để có thể vào được đại học. Để đạt được mục tiêu này, cậu thành lập một nhóm học tập với một nhóm bạn học đa dạng. Cùng nhau, họ đối mặt với những thử thách trong cuộc sống học đường, bao gồm áp lực học hành, nạn bắt nạt và đủ thứ vấn đề khác của tuổi mới lớn.",
  },
  {
    title: "Conan",
    slug: "tham-tu-lung-danh-conan",
    episodes: 1208,
    genres: "Hài Hước, Phá Án, Trinh Thám, Anime",
    poster: IMG_BASE + "Detective Conan.jpg",
    banner: IMG_BASE + "Detective Conan.jpg",
    desc: "Phim hoạt hình Conan bắt đầu sau vụ việc xảy ra tại công viên giải trí nổi tiếng Tropical Land tại khu tàu lượn siêu tốc. Kudo đang điều tra một trong hai người đàn ông có vẻ ngoài khả nghi được cho là nghi phạm trong vụ việc. Anh ta bị tấn công bởi một trong số họ có mật danh là Gin và đồng đội của anh ta tên là Vodka. Sau khi đánh Shinichi, Gin đã đưa cho anh ta một loại thuốc mà sau này được gọi là APTX 4869 để giết anh ta. Trên thực tế, chất độc có một tác dụng phụ hiếm gặp, biến Shinichi từ một cơ thể trưởng thành thành một đứa trẻ thay vì giết chết. Sau sự cố quan trọng, Shinichi về nhà và lấy tên là Conan Edogawa sau khi bị người bạn thời thơ ấu Ran gây áp lực. Shinichi đã cố gắng che giấu danh tính bí mật của mình với những người anh quan tâm để điều tra về tổ chức Áo Đen.",
  },
  {
    title: "Weak Hero Class 1",
    slug: "nguoi-hung-yeu-duoi",
    episodes: 8,
    genres: "Chính Kịch, Học Đường, Hành Động, Hàn Quốc",
    poster: IMG_BASE + "Weak Hero Class 1.jpg",
    banner: IMG_BASE + "Weak Hero Class 1.jpg",
    desc: "Tại một ngôi trường chìm trong chế độ phân cấp bạo lực, thiếu niên trầm tính nọ đã thách thức hiện trạng này, mạo hiểm tất cả để bảo vệ những người bạn đáng để cậu chiến đấu.",
    group: "weak-hero",
    partName: "Weak Hero Class 1",
  },
  {
    title: "Weak Hero Class 2",
    slug: "nguoi-hung-yeu-duoi-2",
    episodes: 8,
    genres: "Chính Kịch, Học Đường, Hành Động, Hàn Quốc",
    poster: IMG_BASE + "Weak Hero Class 2.jpg",
    banner: IMG_BASE + "Weak Hero Class 2.jpg",
    desc: "Tại một ngôi trường chìm trong chế độ phân cấp bạo lực, thiếu niên trầm tính nọ đã thách thức hiện trạng này, mạo hiểm tất cả để bảo vệ những người bạn đáng để cậu chiến đấu.",
    group: "weak-hero",
    partName: "Weak Hero Class 2",
  },
  {
    title: "Gyeongseong Creature (Season 1)",
    slug: "nguoi-hung-yeu-duoi-2",
    episodes: 10,
    genres: "Khoa Học, Viễn Tưởng, Bí Ẩn, Hành Động, Hàn Quốc",
    poster: IMG_BASE + "Gyeongseong Creature (Season 1).jpg",
    banner: IMG_BASE + "Gyeongseong Creature (Season 1).jpg",
    desc: "Ở Gyeongseong năm 1945, giữa thời kỳ Seoul bị thực dân thống trị, một doanh nhân và một do thám chiến đấu để sinh tồn và đối mặt với quái vật sinh ra từ lòng tham của con người.",
    group: "Gyeongseong",
    partName: "Gyeongseong Creature 1",
  },
];

module.exports = globalMoviesList;
